### ISSUE TITLE
Quicklisp and/or Ultralisp ?

### ISSUE THREAD

**Issue by vindarel** [libre-man/cl-transmission#4]
Hey,
I plan in incorporating cl-transmission into an app of mine, and it would be easier if it was on Quicklisp. You can also add it to Ultralisp, it's two clicks away!

thanks

http://ultralisp.org/

**Comment by libre-man** [comment]
Hi,

I will try to this next weekend, as I hope to be able to write some tests for some basic functionality then too. I will keep you posted!

**Comment by vindarel** [comment]
up :) Your package works©, it'd ease distribution for me if it was on Quicklisp, thanks!

**Comment by vindarel** [comment]
Quicklisp's maintainer added cl-transmission so that cl-torrents won't fail, that was a nice surprise. https://github.com/quicklisp/quicklisp-projects/commit/ffb927807ad51d678102c811bb63f730d307ca07

http://blog.quicklisp.org/2019/11/november-2019-quicklisp-dist-update-now.html
