### ISSUE TITLE
February, 2020: the dependency x.let-star makes cl-transmission to be removed from QL

### ISSUE THREAD

**Issue by vindarel** [libre-man/cl-transmission#6]
Hello,

Seen on http://blog.quicklisp.org/2020/02/february-2020-quicklisp-dist-update-now.html

x.let-star disappeared: https://github.com/ks/X.LET-STAR (followed from http://quickdocs.org/x.let-star/)

**Comment by vindarel** [comment]
QL request: https://github.com/quicklisp/quicklisp-projects/issues/1808

**Comment by libre-man** [comment]
Ah, I will remove the dependency.

**Comment by libre-man** [comment]
This was fixed in 488b5f8.

**Comment by phoe** [comment]
I have mailed the repository owner and the repo was made public again. 488b5f8 can be reverted.
